In [1]:
import numpy as np
print(np.__version__)

2.2.6


In [2]:
import numpy as np
arr=np.zeros(5)
print(arr)
arr.dtype
arr.astype(np.int32)

[0. 0. 0. 0. 0.]


array([0, 0, 0, 0, 0], dtype=int32)

In [3]:
arr1=np.ones(5,dtype="int")
print(arr1)
print(arr1.dtype)
print(arr1.shape)


[1 1 1 1 1]
int64
(5,)


In [5]:
arr=np.array([[10,2,30],[4,50,6],[70,8,9],[11,12,13]])
print("Array",arr)
print("shape",arr.shape)
print("datatype",arr.dtype)

Array [[10  2 30]
 [ 4 50  6]
 [70  8  9]
 [11 12 13]]
shape (4, 3)
datatype int64


In [6]:
#to interchange the axis, row become column,column become row
print("swappaxes",np.swapaxes(arr,0,1))

swappaxes [[10  4 70 11]
 [ 2 50  8 12]
 [30  6  9 13]]


In [7]:
#rearrange columns
print("Reshape array",arr.reshape(3,4))

Reshape array [[10  2 30  4]
 [50  6 70  8]
 [ 9 11 12 13]]


In [8]:
print("sort in aixs=0",np.sort(arr,axis=0))
print("sort in axis=1",np.sort(arr,axis=1))

sort in aixs=0 [[ 4  2  6]
 [10  8  9]
 [11 12 13]
 [70 50 30]]
sort in axis=1 [[ 2 10 30]
 [ 4  6 50]
 [ 8  9 70]
 [11 12 13]]


In [11]:
#for printing max and min elemet from array
print("max element",np.max(arr))
print("min element",np.min(arr))

max element 70
min element 2


In [ ]:
#creating range between array
np.linspace(1,10,num=5)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [13]:
arr1=np.zeros((4,3),dtype="int")
print(arr1)
print(arr1.shape)
print(arr1.dtype)
print(arr1.size)

[[0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]]
(4, 3)
int64
12


In [14]:
#Create 1 array and check its dimension
array1=np.array([1,2,3,4,5,6,7])
array1.ndim

1

In [ ]:
#check the size of above array
array1.size

7

In [19]:
#check the shape of array
array1.shape

(7,)

In [22]:
#check the index of second element
array1[1]
#check the index of last element
array1[-1]

np.int64(7)