In [ ]:
# NAME : Rahane Kaveri Bhagwat
# Roll no:111
# Batch:T2
# Assignmnet No :1

2.2.6


In [16]:
import numpy as np
print(np.__version__)

2.2.6


In [2]:
import numpy as np
arr=np.zeros(5)
print(arr)
arr.dtype
arr.astype(np.int32)

[0. 0. 0. 0. 0.]


array([0, 0, 0, 0, 0], dtype=int32)

In [3]:
arr1=np.ones(5,dtype="int")
print(arr1)
print(arr1.dtype)
print(arr1.shape)


[1 1 1 1 1]
int64
(5,)


In [5]:
arr=np.array([[10,2,30],[4,50,6],[70,8,9],[11,12,13]])
print("Array",arr)
print("shape",arr.shape)
print("datatype",arr.dtype)

Array [[10  2 30]
 [ 4 50  6]
 [70  8  9]
 [11 12 13]]
shape (4, 3)
datatype int64


In [6]:
#to interchange the axis, row become column,column become row
print("swappaxes",np.swapaxes(arr,0,1))

swappaxes [[10  4 70 11]
 [ 2 50  8 12]
 [30  6  9 13]]


In [7]:
#rearrange columns
print("Reshape array",arr.reshape(3,4))

Reshape array [[10  2 30  4]
 [50  6 70  8]
 [ 9 11 12 13]]


In [8]:
print("sort in aixs=0",np.sort(arr,axis=0))
print("sort in axis=1",np.sort(arr,axis=1))

sort in aixs=0 [[ 4  2  6]
 [10  8  9]
 [11 12 13]
 [70 50 30]]
sort in axis=1 [[ 2 10 30]
 [ 4  6 50]
 [ 8  9 70]
 [11 12 13]]


In [11]:
#for printing max and min elemet from array
print("max element",np.max(arr))
print("min element",np.min(arr))

max element 70
min element 2


In [ ]:
#creating range between array
np.linspace(1,10,num=5)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [13]:
arr1=np.zeros((4,3),dtype="int")
print(arr1)
print(arr1.shape)
print(arr1.dtype)
print(arr1.size)

[[0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]]
(4, 3)
int64
12


In [14]:
#Create 1 array and check its dimension
array1=np.array([1,2,3,4,5,6,7])
array1.ndim

1

In [ ]:
#check the size of above array
array1.size

7

In [19]:
#check the shape of array
array1.shape

(7,)

In [22]:
#check the index of second element
array1[1]
#check the index of last element
array1[-1]

np.int64(7)

In [3]:
# arrange and reshape the array
array1=np.arange(2,11)
b=array1.reshape(3,3)
b

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10]])

In [4]:
#arithmetic operations
x=np.array([[1,2,3],[2,3,4]])
y=np.array([[10,11,12],[13,14,15]])
print(x)
print(y)
z=x+y
print("------------------")
print(z)

[[1 2 3]
 [2 3 4]]
[[10 11 12]
 [13 14 15]]
------------------
[[11 13 15]
 [15 17 19]]


In [5]:
#arithmetic operations
x=np.array([[1,2,3],[2,3,4]])
y=np.array([[10,11,12],[13,14,15]])
print(x)
print(y)
z=x-y
print("------------------")
print(z)

[[1 2 3]
 [2 3 4]]
[[10 11 12]
 [13 14 15]]
------------------
[[ -9  -9  -9]
 [-11 -11 -11]]


In [6]:
#arithmetic operations
x=np.array([[1,2,3],[2,3,4]])
y=np.array([[10,11,12],[13,14,15]])
print(x)
print(y)
z=x*y
print("------------------")
print(z)

[[1 2 3]
 [2 3 4]]
[[10 11 12]
 [13 14 15]]
------------------
[[10 22 36]
 [26 42 60]]


In [7]:
#arithmetic operations
x=np.array([[1,2,3],[2,3,4]])
y=np.array([[10,11,12],[13,14,15]])
print(x)
print(y)
z=x/y
print("------------------")
print(z)

[[1 2 3]
 [2 3 4]]
[[10 11 12]
 [13 14 15]]
------------------
[[0.1        0.18181818 0.25      ]
 [0.15384615 0.21428571 0.26666667]]


In [8]:
#arithmetic operations
x=np.array([[1,2,3],[2,3,4]])
y=np.array([[10,11,12],[13,14,15]])
print(x)
print(y)
z=x**y
print("------------------")
print(z)

[[1 2 3]
 [2 3 4]]
[[10 11 12]
 [13 14 15]]
------------------
[[         1       2048     531441]
 [      8192    4782969 1073741824]]


In [9]:
?array1

Type:        ndarray
String form: [ 2  3  4  5  6  7  8  9 10]
Length:      9
File:        c:\users\admin\appdata\local\programs\python\python313\lib\site-packages\numpy\__init__.py
Docstring:  
ndarray(shape, dtype=float, buffer=None, offset=0,
        strides=None, order=None)

An array object represents a multidimensional, homogeneous array
of fixed-size items.  An associated data-type object describes the
format of each element in the array (its byte-order, how many bytes it
occupies in memory, whether it is an integer, a floating point number,
or something else, etc.)

Arrays should be constructed using `array`, `zeros` or `empty` (refer
to the See Also section below).  The parameters given here refer to
a low-level method (`ndarray(...)`) for instantiating an array.

For more information, refer to the `numpy` module and examine the
methods and attributes of an array.

Parameters
----------
(for the __new__ method; see Notes below)

shape : tuple of ints
    Shape of created array

In [14]:
import numpy as np

# Create a sample array
arr = np.array([10, 20, 5, 30, 25])

# Get index of maximum value
max_index = np.argmax(arr)
print("Index of maximum value:", max_index)
print("Maximum value:", arr[max_index])

# Get index of minimum value
min_index = np.argmin(arr)
print("Index of minimum value:", min_index)
print("Minimum value:", arr[min_index])


Index of maximum value: 3
Maximum value: 30
Index of minimum value: 2
Minimum value: 5
